Avatars
gurovoleg/webdev-team04 pull request #13
Opened 2018-08-02 12:25 UTC by Lareta064

внесены изменения в миксины для аватарок. Теперь картинка вложена в див с классом либо avatar, либо avatar--small.  вы говорили, что  в данном случае не очень правильно задавать class в виде параметра, но к сожалению не подсказали, как правильно :)  Поэтому внесла изменения на свое усмотрение

2018-08-02 16:42 UTC, nobleworkshop commented on src/less/blocks/_avatars.less
> +	width: 200px;
Размер по макету должен быть 205px X 205px

2018-08-02 16:48 UTC, nobleworkshop requested changes
Изменить размер большой аватарки.
Использовать BEM naming:

block block--modifier

2018-08-02 18:28 UTC, Lareta064 commented
изменения внесены с учетом рекомендаций: размер большой аватарки 205х205, и учтен БЭМ нейминг

2018-08-03 09:39 UTC, nobleworkshop approved these changes
Все отлично!)

2018-08-03 09:39 UTC, merged