ui buttons ready
gurovoleg/webdev-team04 pull request #14
Opened 2018-08-02 13:31 UTC by Vyacheslav-073

всё переделал код сократился % на 50 посмотрите пожалуйста может ещё что то можно оптимизировать

2018-08-02 16:33 UTC, nobleworkshop requested changes
Уже намного лучше. 
Есть правки. Комментарии в коде. 

И еще:

1) кнопка Войти - когда уводишь курсор нет плавного перехода. Надо добавить.

2) Попробовать в кнопку с иконкой добавитm параметр, чтобы передавать в него классы иконки font awesome

2018-08-02 16:33 UTC, nobleworkshop commented on src/pug/mixins/_buttons.pug
> +mixin button--edit(text, link)
Сделать название миксинов в виде:
button-edit

То есть вместо двойного дефиса "--" написать → "-"
И так для всех миксинов.

Между миксинами добавить 1ну строку отступа, для удобства чтения кода.

2018-08-02 16:36 UTC, nobleworkshop commented on src/pug/mixins/_buttons.pug
> +	a(class="button--edit" href=link) #{text}
Мы используем BEM naming? поэтому rkcc который принимает кнопка должен быть
button button--edit

и так же для других кнопок

2018-08-03 08:28 UTC, Vyacheslav-073 commented
сделал правки теперь всё должно быть ок

2018-08-03 10:00 UTC, nobleworkshop approved these changes
Все отлично!)

2018-08-03 10:01 UTC, merged