Ui badges
gurovoleg/webdev-team04 pull request #16
Opened 2018-08-02 15:53 UTC by Lareta064

миксин для бейджа. фоновый цвет в виде переменной не работает, возможно из-за того, что background-color прописан инлайново в паг файле

2018-08-02 17:07 UTC, nobleworkshop requested changes

2018-08-02 17:07 UTC, nobleworkshop commented on src/pug/mixins/_badges.pug
> +	.badge(style="background-color: " + bgColor) #{text}
параметр bgColor надо убрать. У нас бейдж только одно цвета.

Сделайте дополнительный вариант, если бейдж будет ссылкой, чтобы он корректно отображался, в.т.ч. по клику, ховеру.

2018-08-02 17:35 UTC, nobleworkshop requested changes
Надо сделать и просто бейдж и ссылку. Обсудили онлайн.

2018-08-02 18:01 UTC, Lareta064 commented
Два вида бейджиков: обычный и ссылка, сделаны в виде миксинов

2018-08-02 18:19 UTC, nobleworkshop approved these changes
Отлично!) Все верно!)

2018-08-02 18:20 UTC, nobleworkshop commented
@Lareta064 Сделайте разрешение конфликтов и делайте мерж. После отметьте задачу как выполненную. Отлично, первая задача закрыта!)

2018-08-03 10:10 UTC, nobleworkshop approved these changes
Looks good!)

2018-08-03 10:10 UTC, merged