footer is NOT ready
gurovoleg/webdev-team04 pull request #17
Opened 2018-08-02 16:51 UTC by victorsharamet

Не понимаю где мне увидеть хотя бы свои изминения для футера, чтобы код был виден. Подключаю на странице, но ничего не показывается. Что и где я делаю не так? Как увидеть футер и где его отобразить правильно?

2018-08-02 17:15 UTC, nobleworkshop commented
Промежуточный результат посмотрели на онлайн разборе, в Четверг вечером. Надо продолжать работу.

2018-08-02 17:37 UTC, nobleworkshop commented
Надо править дальше. Поправить локально, в этой же ветке и потом отправить на сервер git pull

2018-08-02 21:13 UTC, victorsharamet commented
1) Для ссылок border-bottom оставляем? В коде есть такая строка уже, но в макете подчеркивания нету у ссылок.
2) Как можно было еще оформить текст с классом copyright? Чтобы может упростить.
3) Проверил на PixelPerfect. Пришлось вписать дополнительные padding/margin. Такое лучше делать глобально где-то сразу, или для футера/хедера можно отдельно в less написать стили?

2018-08-03 10:52 UTC, nobleworkshop requested changes
Обсудили онлайн.
Сделать футер по сетке.
Как оптимизировать код - посмотрели.

2018-08-03 10:52 UTC, nobleworkshop commented on src/less/sections/_footer.less
> +            font-family: 'Open sans';
Базовый шрифт уже задан в base.less

2018-08-03 10:52 UTC, nobleworkshop commented on src/less/sections/_footer.less
> +    font-family: 'Myriad Pro';
Этот шрифт убрать. В макете везде Open Sans

2018-08-05 22:25 UTC, victorsharamet commented
1. Какое поведение должно быть у ссылок по active?
2. Как заставить сердце биться? Используя @keyframes и animation: heartbeat 2s infinite.

2018-08-06 10:06 UTC, nobleworkshop approved these changes
Все верно!) Готово!)

2018-08-06 10:06 UTC, nobleworkshop commented on src/pug/sections/footer.pug
>  		.footer-nav__item.copyright
.footer-nav__item  переименовать в .footer__item

иначе он будет являться элементом блока .footer-nav , а это не так.

2018-08-06 10:06 UTC, nobleworkshop commented on src/pug/mixins/_mixins.pug
> +					li
Зачем такие отступы большие?)

2018-08-06 10:19 UTC, merged