ui-header-admin
gurovoleg/webdev-team04 pull request #23
Opened 2018-08-03 22:37 UTC by Lareta064

Сверстана панель Админа. Пункты меню реализованы в виде миксина, который описан в файле mixins/_admin-nav.pug  Для блока  .user-info   использованы ранее созданные миксины для элементов avatars  и  badges. Блок назвала не admin-info  , а user-info, так как его можно использовать для верстки аналогичного блока в Шапке Пользователь

2018-08-04 12:37 UTC, nobleworkshop requested changes
Хоро. Есть моменты для правки. Чтобы применить более универсальные подходы.

Поправить отображение шапки в документации.

Вынести ссылку на шапку в документации.

В документации указать код подключения и код верстки секции в pug

2018-08-04 12:37 UTC, nobleworkshop commented on src/less/sections/_header-admin.less
> +	width: 80%;
Ширину в 80% убрать, сделать по другому. Рассмотрели на МК,

2018-08-04 12:37 UTC, nobleworkshop commented on src/pug/sections/header-admin.pug
> +.header-admin.pt-30.pb-30
Все паддинги перенести в CSS, и добавить паддинги слева и справа.

2018-08-04 12:37 UTC, nobleworkshop commented on src/less/sections/_header-admin.less
> +	position: absolute;
Избавиться от абсолюта.

2018-08-05 10:40 UTC, Lareta064 commented
Изменила верстку полностью с учетом рекомендаций. Маргины между элементами заданы с учетом паддингов, чтобы в сумме было, как на макете. То есть между ссылками на макете  расстояние 30 пиксель. По верстке у ссылок есть паддинги справа и слева по 5 пиксель итого 5+5 =10 пкс, по этому с учетом этого, между ссылками задавала маргин   20пиксель  И тогда 20 + 10 = 30 пикселькак на макете

2018-08-06 09:35 UTC, nobleworkshop requested changes
К аватаркам добавить свойство
flex-shrink: 0;
чтобы они не сжимались когда аватарке не хватает места

Бейджик сделать ссылкой, и чтобы текст оставался белым.

2018-08-06 09:57 UTC, Lareta064 commented
внесены изменения flex-shrink, для фото аватарки,  и бейдж заменен на  бейдж-ссылку

2018-08-06 10:02 UTC, nobleworkshop approved these changes
Все верно!) Задача готова!

2018-08-06 10:02 UTC, merged