Button profile fix
gurovoleg/webdev-team04 pull request #34
Opened 2018-08-06 19:00 UTC by Vyacheslav-073

все изменения в цвет внёс и по ховер и актив тоже и текст 13пикс задал, прошу прощения за невнимательность

2018-08-07 10:57 UTC, nobleworkshop requested changes
Нужны правки. Нет прозрачности. Комментарий в коде.

2018-08-07 10:57 UTC, nobleworkshop commented on src/less/blocks/_buttons.less
> +	background: lighten(black, 75%);
Сейчас у вас на выходе серый цвет.
А нужен черный с прозрачностью.
Надо исправить.

Сейчас:
`border-color: #bfbfbf;`

Должно быть:
`background: rgba(34, 34, 34, 0.25);`

Аналогично и для рамки.
После буду проверять дальше.

2018-08-07 11:37 UTC, Vyacheslav-073 commented
посмотрите пожалуйста

2018-08-07 11:42 UTC, nobleworkshop commented
@Vyacheslav-073 Цвет задан верно. А что с рамкой? Она вообще нужна для кнопки с Профилем? Что у нас в дизайне?

2018-08-07 12:04 UTC, Vyacheslav-073 commented
убрал border теперь уже должно быть всё

2018-08-07 15:26 UTC, Vyacheslav-073 commented
все правки сделаны и добавлена возможность позиционирования кнопок

2018-08-07 20:24 UTC, Vyacheslav-073 commented
работа готова к контрольной проверке

2018-08-08 00:37 UTC, gurovoleg approved these changes
Отлично потрудился!

2018-08-08 00:37 UTC, merged