Ui card new
gurovoleg/webdev-team04 pull request #36
Opened 2018-08-06 19:16 UTC by Vyacheslav-073

новую ветку создал проверьте пожалуйста

2018-08-07 11:08 UTC, nobleworkshop requested changes
Есть моменты для правки.

Комментарии в коде.
Оставил к карточке с постом. К карточке с работой - они тоже справедливы, и применимы.

Проработайте вариант если у карточки заголовок в одну или в 2 строки. Чтобы кнопка всегда была внизу. И карточки были одинаковой высоты.

2018-08-07 11:08 UTC, nobleworkshop commented on src/pug/mixins/_cards.pug
> +				p
Для заголовка сделать тег h3 и дать ему класс .card__title

2018-08-07 11:08 UTC, nobleworkshop commented on src/pug/mixins/_cards.pug
> +			.card__body-text
Эту обертку  .card__body-text удалить.

2018-08-07 11:08 UTC, nobleworkshop commented on src/pug/mixins/_cards.pug
> +				p
Не забудьте про semibold и высоту строки

2018-08-07 14:14 UTC, closed without merging

2018-08-08 16:15 UTC, Vyacheslav-073 commented
подгонял в perfect picksel проверьте пожалуйста

2018-08-08 18:20 UTC, Vyacheslav-073 commented
извиняюсь добавил изменения в pre.