Ui comments
gurovoleg/webdev-team04 pull request #38
Opened 2018-08-06 21:13 UTC by Lareta064

секция комментарии:  1. аватарка добавлена миксином ,  2. контент комментария так же прописан в миксин  (путь /pug/mixins/_comments.pug)  Знаю, что не так добавляются дата и время (скорее всего должны встать автоматически)   :(    Юрий, очень хочется хоть раз сверстать что-нибудь и не расстраивать Вас, но это точно не в этот раз :(

2018-08-07 06:51 UTC, Lareta064 commented
В коммите "ui-comments-before-registration" разместила  свой код для блока "комментарии "  над кодом блока "регистрация"

2018-08-07 11:20 UTC, nobleworkshop requested changes
Добавьте в тег pre пример вызова миксина, как быстро получить этот блок одной строкой.

Обсудили онлайн. Перенести все в миксин или в секцию.

2018-08-07 16:25 UTC, Lareta064 commented
чтобы посмотреть работу в браузере, выбираем Секции - Комментарии .  А чтобы посмотреть блок с кодом в теге .pre выбираем Блоки - Комментарии

2018-08-08 10:47 UTC, nobleworkshop approved these changes
Задача готова!)

2018-08-08 10:47 UTC, merged