ui-register-comment ready
gurovoleg/webdev-team04 pull request #5
Opened 2018-08-02 08:04 UTC by AnatoliyNBulyga

Сделал "Блок регистрация"

2018-08-02 09:42 UTC, nobleworkshop commented on src/less/blocks/_comment.less
> +	height: 300px;
Убрать фиксированную высоту, добавить вместо нее паддинги сверху и снизу.

2018-08-02 09:43 UTC, nobleworkshop commented on src/less/blocks/_comment.less
> +.comment-register {
Добавить фон к этому блоку.Цвет фона сделать через переменную. И записать ее в глобальные less переменные - в файл vaiables less

2018-08-02 09:46 UTC, nobleworkshop requested changes
Проверить размер текста в блоке. Высота строки.

2018-08-02 10:15 UTC, AnatoliyNBulyga commented
@nobleworkshop пофиксил. 
Убрал высоту блока, 
поставил padding, 
добавил через переменную main-bg - цвет фона
добавил font-size для тега p внутри блока

2018-08-02 10:27 UTC, AnatoliyNBulyga commented
@nobleworkshop в последнем коммите я просто изменил название переменной фона

2018-08-02 10:31 UTC, AnatoliyNBulyga commented
@gurovoleg пофиксил.
Убрал высоту блока,
поставил padding,
добавил через переменную main-bg - цвет фона
добавил font-size для тега p внутри блока

2018-08-02 10:41 UTC, AnatoliyNBulyga commented
@nobleworkshop @gurovoleg изменил padding

2018-08-02 17:23 UTC, nobleworkshop requested changes
Осталось еще немного)

2018-08-02 17:23 UTC, nobleworkshop commented on src/less/blocks/_comment.less
>  		text-align: center;
Сейчас у тега <p> есть свои отступы сверху и снизу, они увеличивают высоту блока. Надо их убрать. Сбросить в ноль.

![image](https://user-images.githubusercontent.com/12967597/43599845-8db718ae-9691-11e8-83c5-2a424db9547c.png)


![image](https://user-images.githubusercontent.com/12967597/43599864-9b155538-9691-11e8-9d19-b5702679224c.png)

2018-08-02 17:23 UTC, nobleworkshop commented on src/pug/pages/ui/comment-register.pug
> +			.comment-register
Поместить этот в .section-ui

2018-08-02 17:23 UTC, nobleworkshop commented on src/pug/pages/ui/comment-register.pug
> +			.comment-register
Это даст доп отступ сверху

2018-08-03 06:55 UTC, AnatoliyNBulyga commented
Пофиксил, плюс добавил цвет текста.

2018-08-03 07:57 UTC, gurovoleg commented on src/less/base/_variables.less
> +@text: #383737;
Надо изменить название из-за конфликта.

2018-08-03 07:57 UTC, gurovoleg requested changes
Переименуй переменную или используй уже готовую. У тебя ее нет, потому что видимо не сделал pull request.

2018-08-03 10:56 UTC, nobleworkshop approved these changes
Looks good!)

2018-08-03 10:57 UTC, merged