about-me-edit
gurovoleg/webdev-team04 pull request #51
Opened 2018-08-08 09:23 UTC by ragimoff

Страница Обо-мне. Редактировать - Технологии готова

2018-08-08 11:12 UTC, nobleworkshop requested changes
Используйте уже готовый миксин с инпутом из документации.

2018-08-08 15:56 UTC, ragimoff reviewed
Input поправил. А остальные изменения они пока так не для проверки.  Я работаю над другой частью

2018-08-09 07:42 UTC, gurovoleg requested changes
Разбить на ветки с учетом нового задания.
Иcпользовать готовый input

2018-08-09 07:57 UTC, ragimoff reviewed
input поправил.

2018-08-09 08:36 UTC, gurovoleg approved these changes
Отлично! Разобрались )

2018-08-09 08:36 UTC, merged