Edit job new
gurovoleg/webdev-team04 pull request #54
Opened 2018-08-08 17:30 UTC by Lareta064

страница Обо мне-опыт работы

2018-08-08 18:03 UTC, Lareta064 commented
Новая версия страницы Обо мне -опыт работы.

2018-08-08 21:12 UTC, Lareta064 commented
не мудрила, не усложняла, просто использовала компоненты из папки ui/user-message.pug   и  ui/forms.pug

2018-08-09 09:18 UTC, gurovoleg reviewed
Посмотреть и убрать возможно лишние обертки.
Убрать класс для кнопки.

2018-08-09 09:19 UTC, gurovoleg commented on src/less/pages/aboutme-edit-job.less
> +.button--removesmall{
Этот класс удали. Я поправил кнопки.

2018-08-09 09:39 UTC, nobleworkshop requested changes
Небольшая правка. Поправьте и делайте мерж.

2018-08-09 09:39 UTC, nobleworkshop commented on src/pug/pages/aboutme-edit-job.pug
> +							.user-message__text
У CSS класса "user-message__text" убрать отступ справа

2018-08-09 18:10 UTC, Lareta064 commented
отступ  справа у текста убрала, кнопку сделала, как на макете

2018-08-10 10:26 UTC, nobleworkshop requested changes
Поправьте и будем проверять еще раз.

2018-08-10 10:26 UTC, nobleworkshop commented on src/less/main.less
> +<<<<<<< HEAD
Эти конструкции от Git после мержа и фикса конфликтов надо удалять:

<<<<<<< HEAD

и

=======

2018-08-10 10:26 UTC, nobleworkshop commented on src/less/main.less
> +>>>>>>> a5d69da0a9ca72dde0eddf2ae0ab711431927638
Это тоже надо удалить.

2018-08-10 12:14 UTC, merged