Feedback page
gurovoleg/webdev-team04 pull request #57
Opened 2018-08-08 20:43 UTC by Lareta064

Страница Сообщения - контакты

2018-08-09 09:33 UTC, nobleworkshop requested changes
Небольшая правочка. Поправьте, разрешите конфликты и делайте мерж.

2018-08-09 09:33 UTC, nobleworkshop commented on src/pug/pages/feedback.pug
> +					.user-message__text
У класса user-message__text отступ справа не нужен. Надо убрать его в LESS

2018-08-09 16:00 UTC, Lareta064 commented
Кнопки теперь как на макете, и у текста убрали маргин 4em справа

2018-08-10 10:20 UTC, nobleworkshop approved these changes
Все отлично!) Разрешите конфликты и делайте мерж.

2018-08-10 11:22 UTC, merged