Checkbox
gurovoleg/webdev-team04 pull request #6
Opened 2018-08-02 08:35 UTC by Ivanova-Zinaida

Готовые чекбоксы, два вида в активном состояние и неактивном состояние

2018-08-02 09:49 UTC, nobleworkshop commented on src/pug/mixins/_forms.pug
> +mixin checkbox(type, name, text, status)
Убрать аргумент type, потому как в миксине с названием checkbox - type всегда будет равен checkbox

2018-08-02 09:53 UTC, nobleworkshop requested changes
Сейчас иконка "галочки" не отображается. 
Надо сделать чтобы отображалась.

2018-08-02 17:25 UTC, nobleworkshop requested changes
Чекбоксы не работают. Напишите в чат если не получается сделать, или если у вас все ок. Тогда будем разбираться.

2018-08-02 19:32 UTC, Ivanova-Zinaida commented
Добавила изменения из удаленной ветки девелоп и все вроде перестало конфликтовать., Все не работало из за того что убрала аргумент type. Так что вернула его. у меня все работает в нескольких браузерах.

2018-08-03 10:21 UTC, nobleworkshop approved these changes
Loks good!)

2018-08-03 10:21 UTC, merged