login-and-registration-edit
gurovoleg/webdev-team04 pull request #63
Opened 2018-08-09 18:55 UTC by ragimoff

Работаю в файле login.pug
1 -- Проблема с блоком которая расопологается под блоком заполнения регистрации. Задал position: absolute блоку регистрации и position: relative блока который под ним который прозрачный. При увеличении расходятся блоки. Когда накладываю блок с регистрацией на блок прозрачный из за opacity блок с регистрацией так же просвечивается.
2 -- Картинка background я залил другую так как у той которая в макете psd со слоями. обьеденил слои. можно было конечно играться с тенью но так как в макете не получается.
3 -- Заголовок h1 Со словом регистрации привязан к блоку user-content и задается цвет черный. задаю отдельным классом чтоб поставить цвет белый не меняется.
4 -- input mixin имеет блок form-group и добавляются лишние margin и стили из за которых не работают мои стили которые я прописываю другим классом. или нужно делать отдельно другие input или как то исправить эти.
5 -- работа остановилась вот на этих проблемах.

2018-08-10 10:31 UTC, nobleworkshop commented on src/pug/pages/login.pug
> +			.login-form
.login-form должен быть внутри .login-form__background.col-lg-4
и никакого абсолюта не надо

2018-08-10 10:36 UTC, nobleworkshop commented
1) Блок с формой должен быть внутри блока с плашкой, тогда и абсолют не понадобиться.

2) По картинке Ок. Можно было сделать фон поверх картинки градиентов.

3) Здесь югыук-content- не нужен. Его можно смело убирать. Для зоговлока можете дать дополнительный класс. В случае необходимости используйте important

4) Сделайте отдельный миксин под эти 2 инпута.

5) На все ответил, в видеоразборе в Пт посмотрели.

2018-08-10 22:43 UTC, ragimoff reviewed
1. Блок с формой должен быть внутри блока с плашкой, тогда и абсолют не понадобиться.

Это Юрий ваш комментарий к моему вопросу про наложение блоков. Я этот момент в вопросе тоже описал, просто вы не поняли меня. Вернее я не точно обьяснил. Я когда делаю наложения блоков, opacity который задан для первого дает на все вложенные блоки такой же opacity и все блоки прозрачные становятся. не могу просто именно с этим моментом разобратся

2. У чекбоксов с классом form-checkbox стоял width 15%  убрал его вообще так как в моем случае он мешал слова переносились на нижнюю строчку

А так все остальное сделал.

2018-08-11 10:44 UTC, nobleworkshop requested changes
1) Момент по opacity и прозрачности. У блока .login-form__background--registration убрать opacity? для прозрачности фона - задать ему цвет через rgba

2) Отступ от поля "Пароль" до чекбокса должен быть 20px 

3) Футер должен быть прижат к низу страницы. В тег html задать высоту 100%. Внимательно посмотреть чтобы это не отразилось на других страницах сайта. Рассмотрели на МК.

После будем проверять далее.
Постарайтесь побыстрее закрыть эту задачу.

2018-08-13 18:23 UTC, closed without merging